# Generated by Django 3.1.7 on 2021-03-22 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import roommates.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('NB', 'Nonbinary'), ('O', 'Other')], default='O', max_length=2)),
                ('pronouns', models.CharField(blank=True, default=roommates.models.Profile.blank_default, max_length=16, null=True)),
                ('bio', models.TextField(blank=True, default=roommates.models.Profile.blank_default, max_length=500, null=True)),
                ('year', models.PositiveSmallIntegerField(default=2021)),
                ('location_general', models.BooleanField(default=True)),
                ('location_specific', models.TextField(blank=True, default=roommates.models.Profile.blank_default, max_length=200)),
                ('relation_status', models.BooleanField(default=True)),
                ('room_status', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
