# Generated by Django 3.1.7 on 2021-03-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
