# Generated by Django 3.1.7 on 2021-04-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0004_auto_20210327_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default_pic.jpg', upload_to='static'),
        ),
    ]
