# Generated by Django 3.1.7 on 2021-04-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0005_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
