# Generated by Django 3.1.7 on 2021-04-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0006_auto_20210405_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default_profile_pic.gif', upload_to='staticfiles/images'),
        ),
    ]
