# Generated by Django 3.1.7 on 2021-04-12 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roommates', '0008_auto_20210405_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(related_name='liked_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
