# Generated by Django 3.2 on 2021-04-19 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roommates', '0011_profile_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked',
            field=models.ManyToManyField(blank=True, default=None, related_name='block', to=settings.AUTH_USER_MODEL),
        ),
    ]
