# Generated by Django 3.1.7 on 2021-04-28 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0012_profile_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(choices=[('UKN', 'Unknown'), ('OTH', 'Other'), ('AE', 'Aerospace Engineering'), ('AAAS', 'African American and African Studies'), ('AS', 'American Studies'), ('ANT', 'Anthropology'), ('ACE', 'Archaeology'), ('ARCH', 'Architectural History'), ('ARC', 'Architecture'), ('ASTR', 'Astronomy'), ('BIS', 'Bachelor of Interdisciplinary Studies'), ('BPS', 'Bachelor of Professional Studies in Health Sciences Management'), ('BIO', 'Biology'), ('BME', 'Biomedical Engineering'), ('CHE', 'Chemical Engineering'), ('CHEM', 'Chemistry'), ('CIVE', 'Civil Engineering'), ('CLAS', 'Classics'), ('COGS', 'Cognitive Science'), ('COMM', 'Commerce'), ('CMPL', 'Comparative Literature'), ('CE', 'Computer Engineering'), ('CS', 'Computer Science'), ('DAN', 'Dance'), ('DRA', 'Drama'), ('EALL', 'East Asian Languages, Literatures and Culture'), ('ECON', 'Economics'), ('EEE', 'Electrical Engineering'), ('ES', 'Engineering Science'), ('ENGL', 'English'), ('ENVR', 'Environmental Sciences'), ('ETP', 'Environmental Thought and Practice'), ('TEP', 'Five-Year Teacher Education Program'), ('FREN', 'French'), ('GERM', 'German'), ('GEMS', 'German Studies'), ('GBL', 'Global Studies'), ('HIST', 'History'), ('HOA', 'History of Art'), ('HBIO', 'Human Biology'), ('IMGS', 'Interdisciplinary Major of Global Studies'), ('JS', 'Jewish Studies'), ('KINE', 'Kinesiology'), ('LAS', 'Latin American Studies'), ('LING', 'Linguistics'), ('MSE', 'Materials Science and Engineering'), ('MATH', 'Mathematics'), ('MECH', 'Mechanical Engineering'), ('MEDA', 'Media Studies'), ('MEDS', 'Medieval Studies'), ('MESA', 'Middle Eastern and South Asian Languages and Cultures'), ('MUS', 'Music'), ('NEUR', 'Neuroscience'), ('NURS', 'Nursing'), ('PHIL', 'Philosophy'), ('PHYS', 'Physics'), ('PST', 'Political and Social Thought'), ('PPPL', 'Political Philosophy, Policy, and Law'), ('POL', 'Politics'), ('PSYC', 'Psychology'), ('RS', 'Religious Studies'), ('SLL', 'Slavic Languages and Literatures'), ('S', 'Sociology'), ('SPAN', 'Spanish'), ('SCD', 'Speech Communication Disorders'), ('STAT', 'Statistics'), ('SA', 'Studio Art'), ('SYS', 'Systems Engineering'), ('UEP', 'Urban and Environmental Planning'), ('WGS', 'Women, Gender & Sexuality'), ('YSI', 'Youth & Social Innovation')], default='UKN', max_length=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.PositiveSmallIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(2021), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
