# Generated by Django 3.1.7 on 2021-04-29 21:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0013_auto_20210428_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='default_profile_pic.gif', max_length=255),
        ),
    ]
