"""
Django settings for roommatefinder project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import sys
import cloudinary
import cloudinary.uploader
import cloudinary.api
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '2cjvd9vdy%77v2$$ynm7y^ip-9&ux*c-5l6a!+193a=mp6@-t0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'roommates.apps.RoommatesConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',   # <--
    
    'allauth',   # <--
    'allauth.account',   # <--
    'allauth.socialaccount',   # <--
    'allauth.socialaccount.providers.google',   # <--
    'allauth.socialaccount.providers.facebook',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'roommatefinder.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'roommatefinder.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
#Title: Django Documentation: Settings
#Author: Django Software Foundation
#Date: last accessed 5/6/21
#Code version: 3.1
#URL:  https://docs.djangoproject.com/en/3.1/ref/settings/#databases
#Software License: BSD-3

# DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.sqlite3',
#             'NAME': BASE_DIR / 'db.sqlite3',
#         }
#     }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
       
        'NAME': 'd124rch2dsnhjs',
       
        'USER': 'ozuanomwmekcwm',
       
        'PASSWORD': 'ad3318ce00000114cc79a6cfbd1847ea6246f4d0ccc50bbc94255724d8b2c135',
       
        'HOST': 'ec2-54-144-251-233.compute-1.amazonaws.com',
       
        'PORT': '5432',
    }
}

if 'test' in sys.argv: 
    DATABASES['default'] = {
     'ENGINE': 'django.db.backends.sqlite3',
     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
       'TEST_NAME': os.path.join(BASE_DIR, 'db.sqlite3')
    }

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators
#Title: Django Documentation: Settings
#Author:Django Software Foundation
#Date: last accessed 5/6/21
#Code version: 3.1
#URL:  https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators
#Software License: BSD-3

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization //this was here with project setup
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'EST'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images) //This was here with project setup
# https://docs.djangoproject.com/en/3.1/howto/static-files/


STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

MEDIA_URL = '/images/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'staticfiles/images')

# https://travis-ci.community/t/django-unit-tests-failing-on-travis-builds/10625/2
#Title: Django Unit Tests failing on Travis builds
#Author: user Montana
#Date: published November 2020, last accessed 5/6/21
#Code version: 3.0
#URL:  https://travis-ci.community/t/django-unit-tests-failing-on-travis-builds/10625/2
#Software License: BSD-3

try:
    # Configure Django App for Heroku. 
    import django_heroku
    django_heroku.settings(locals(), test_runner=False)
except ImportError:
    found = False

AUTHENTICATION_BACKENDS = (
 'django.contrib.auth.backends.ModelBackend',
 'allauth.account.auth_backends.AuthenticationBackend',
 )

SITE_ID = 3
LOGIN_REDIRECT_URL = '/'
ACCOUNT_EMAIL_VERIFICATION = 'none'

SOCIALACCOUNT_PROVIDERS = {
    'google': { 
#Title: in 5 mins: set up Google login to sign up users on Django
#Author:Zoe Chew
#Date: published 7/27/19, last accessed 5/6/21
#Code version: 3.0
#URL:  https://whizzoe.medium.com/in-5-mins-set-up-google-login-to-sign-up-users-on-django-e71d5c38f5d5
#Software License: BSD-3
       'SCOPE': [
            'profile',
           'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }, #Title: Django-allauth Facebook login
        #Author: Kwon Jinhwan
        #Date: published 2/5/17, last accessed 5/6/21
        #Code version: 1.11
        #URL:  https://jinkwon711.medium.com/django-allauth-facebook-login-b536444cbc6b
        #Software License: BSD-3
    'facebook': {
       'METHOD': 'oauth2',
        'SCOPE': ['email','public_profile'], #avoiding app review 
        #Title: Permissions/Login Review
        #Author: Facebook
        #Date: last accessed 5/6/21
        #URL:  https://developers.facebook.com/docs/facebook-login/permissions/review/
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'FIELDS': [
            'email',
            ],
        'EXCHANGE_TOKEN': True,
        'LOCALE_FUNC': lambda request: 'kr_KR',
        'VERIFIED_EMAIL': False,
       'VERSION': 'v2.4'}
} 


cloudinary.config(
cloud_name = 'duu2qerbq',
api_key = '539255188232543',
api_secret ='IY4qhfcHA1k8TklPPW2y8ZK6jDo'

    ) 